baseurl = "https://techstop.github.io/"
languageCode = "en-us"
title = "techStop"
# Define how many posts appear per page
paginate = 6
# For syntax highlighting in code blocks
pygmentsUseClasses = true
theme = "flexxy"

[params]
    # Enable google analytics by entering your tracking code
    googleAnalytics = "UA-114983197-2"
    # Enable google adsesense verification by entering your publisher id
    googleAdsenseVerify = "ca-pub-8645513020646755"
    site_author = "Antonio"
    site_description = "A tech website with focus on linux and android. Check out our tutorials and articles for the linux and android platforms."
    # Leave empty to disable header image
    header_background = "img/techStop_header.png"
    # Leave empty to remove it
    header_title = ""
    # Updates automatically each year on January 1st
    copyright = "<a href=\"https://techstop.github.io/\">techStop</a>"
    # Leave empty to disable navbar site name
	  navbar_site_name = "techStop"	  
	  # Display the post publish date
    post_date = true
    # Display post tags at bottom of post
    post_tags = true
    
    # Remove or leave empty to disable comments globally. Add "comments = false" to post front matter to disable on individual posts. Install the Utterances app in your github to enable Utterances comments. For more info and instructions visit, https://utteranc.es/
    # You only need to install the Utterances app to your github repo, everything else has been configured in Flexxy theme. Then add the username and repo below.
    # Example: (comments = "GITHUB_USERNAME/REPO")
    comments = "techstop/techstop"
    
    custom_css = []
    custom_js  = []

[social]
    # Add your social network account usernames. The links to your accounts will be created automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "GameTheory-"
