baseurl = "https://example.org/"
languageCode = "en-us"
title = "John Doe's blog"
# Define how many posts appear per page
paginate = 8
# Enable google analytics by entering your tracking code
googleAnalytics = ""
theme = "flexxy"

# Remove this line if you use this theme for a real website. This line is only to preview the theme within the exampleSite folder with the hugo server command.
themesDir = "../.."

[params]
    site_author = "John Doe"
    site_description = "The awesome blog of John Doe."    
    # Leave empty to disable header image
    header_background = "img/desk.jpg"
    # Leave empty to remove it
    header_title = "Customizable header title"
    # Updates automatically each year on January 1st
    copyright = "Powered by <a href=\"https://gohugo.io\" target=\"_blank\">Hugo</a>"
    # Leave empty to disable navbar site name
	  navbar_site_name = "John Doe's blog"	  
	  # Display the post publish date
    post_date = true
    # Display post tags at bottom of post
    post_tags = true
    
    # Remove or leave empty to disable comments globally. Add "comments = false" to post front matter to disable on individual posts. Install the Utterances app in your github to enable Utterances comments. For more info and instructions visit, https://utteranc.es/
    # You only need to install the Utterances app to your github repo, everything else has been configured in Flexxy theme. Then add the username and repo below.
    # Example: (comments = "GITHUB_USERNAME/REPO")
    comments = ""
    
    custom_css = []
    custom_js  = []

[social]
    # Add your social network account usernames. The links to your accounts will be created automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "GameTheory-"
